#!/data/data/com.termux/files/usr/bin/bash


#D-link 2740u

curl 'http://192.168.2.1/form2RebootOrReset.cgi' -X POST \
 -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0' \
 -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
 -H 'Accept-Language: en-US,en;q=0.5' \
 -H 'Accept-Encoding: gzip, deflate' \
 -H 'Content-Type: application/x-www-form-urlencoded' \
 -H 'Origin: http://192.168.2.1' \
 -H 'Authorization: Basic YWRtaW46cGFzc3dvcmQ=' \
 -H 'Connection: keep-alive' \
 -H 'Referer: http://192.168.2.1/system.htm' \
 -H 'Upgrade-Insecure-Requests: 1' \
 -H 'Priority: u=4' \
 -H 'Pragma: no-cache' \
 -H 'Cache-Control: no-cache' --data-raw 'saveCurAndReboot=Save+and+reboot&submit.htm%3Freboot.htm=Send'
exit

